import { createFileRoute, Link } from "@tanstack/react-router";
import { Card } from "@/components/ui/card";
import { Mail, FileText, ListChecks, Search, MessageSquare, ArrowRight, Sparkles } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Dashboard — WorkflowAI" },
      { name: "description", content: "Your AI workplace productivity hub." },
    ],
  }),
  component: Dashboard,
});

const tools = [
  { url: "/email", icon: Mail, title: "Smart Email Generator", desc: "Draft professional emails in seconds with the right tone." },
  { url: "/notes", icon: FileText, title: "Meeting Notes Summarizer", desc: "Turn raw notes into clear summaries with action items." },
  { url: "/planner", icon: ListChecks, title: "AI Task Planner", desc: "Break goals into prioritized, time-boxed tasks." },
  { url: "/research", icon: Search, title: "AI Research Assistant", desc: "Get structured briefs and key findings on any topic." },
  { url: "/chat", icon: MessageSquare, title: "AI Chatbot", desc: "A general assistant for any workplace question." },
];

function Dashboard() {
  return (
    <div className="mx-auto w-full max-w-6xl space-y-10">
      <section
        className="relative overflow-hidden rounded-2xl p-8 sm:p-12 text-primary-foreground"
        style={{ background: "var(--gradient-primary)", boxShadow: "var(--shadow-elegant)" }}
      >
        <div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-white/10 blur-3xl" />
        <div className="absolute -bottom-20 -left-20 h-64 w-64 rounded-full bg-white/10 blur-3xl" />
        <div className="relative">
          <div className="inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1 text-xs font-medium backdrop-blur">
            <Sparkles className="h-3.5 w-3.5" /> AI Workplace Suite
          </div>
          <h1 className="mt-4 max-w-2xl text-3xl font-semibold sm:text-4xl">
            Automate the busywork. Focus on what matters.
          </h1>
          <p className="mt-3 max-w-xl text-sm text-white/85 sm:text-base">
            Five AI tools built for professionals — emails, meeting notes, planning, research, and chat — in one clean workspace.
          </p>
          <Link
            to="/chat"
            className="mt-6 inline-flex items-center gap-2 rounded-lg bg-background px-4 py-2.5 text-sm font-medium text-foreground transition hover:bg-background/90"
          >
            Start with Chatbot <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </section>

      <section>
        <h2 className="mb-4 text-lg font-semibold tracking-tight">Tools</h2>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {tools.map((t) => (
            <Link key={t.url} to={t.url} className="group">
              <Card className="h-full p-5 transition-all hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-lg">
                <div
                  className="mb-4 flex h-10 w-10 items-center justify-center rounded-lg text-primary-foreground"
                  style={{ background: "var(--gradient-primary)" }}
                >
                  <t.icon className="h-5 w-5" />
                </div>
                <h3 className="font-display text-base font-semibold">{t.title}</h3>
                <p className="mt-1 text-sm text-muted-foreground">{t.desc}</p>
                <div className="mt-4 flex items-center text-xs font-medium text-primary opacity-0 transition group-hover:opacity-100">
                  Open <ArrowRight className="ml-1 h-3 w-3" />
                </div>
              </Card>
            </Link>
          ))}
        </div>
      </section>

      <section className="rounded-xl border bg-muted/30 p-5 text-sm text-muted-foreground">
        <strong className="font-semibold text-foreground">Responsible AI:</strong> Outputs are generated by AI models and may contain inaccuracies, bias, or outdated information. Always review and edit AI-generated content before sharing externally or using in business decisions. Do not submit confidential or personally identifiable information you are not authorized to share.
      </section>
    </div>
  );
}
